name: Node Continuous Integration

on:
  pull_request:
    branches: [master, dev]

jobs:
  test_pull_request:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: install ffmpeg
        run: |
          sudo apt-get update
          sudo apt-get install ffmpeg
      - run: npm ci
      - run: npm test
      - run: npm run build
